# Generated by Django 3.0.3 on 2020-02-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='esurname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
